name: CI                                                            

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cloudlab-api

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (CI)
        run: docker build -t cloudlab-api:ci .

      - name: Run container (CI)
        run: |
          docker run -d --rm --name cloudlab-ci -p 5000:5000 cloudlab-api:ci
          sleep 3

      - name: Smoke test /health
        run: curl -fsS http://127.0.0.1:5000/health

      - name: Stop container
        if: always()
        run: docker stop cloudlab-ci || true

      # Push ONLY on main branch pushes (not PRs)
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build + tag image for Docker Hub
        if: github.event_name == 'push'
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
      
      - name: Push to Docker Hub
        if: github.event_name == 'push'
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
  
